"""empty message

Revision ID: 573d333beef3
Revises: b467eb57b64d
Create Date: 2019-07-02 12:28:42.696700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573d333beef3'
down_revision = 'b467eb57b64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('crust', sa.String(length=255), nullable=True),
    sa.Column('topping1', sa.String(length=255), nullable=True),
    sa.Column('topping2', sa.String(length=255), nullable=True),
    sa.Column('topping3', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('random_orders')
    # ### end Alembic commands ###
